#!/usr/bin/env bash
# Manual verification driver for the five-lens assertion failure-message change
# (commit ed76465: tests/fm-brief.test.sh no longer cites "the captain's alias"
# in the message emitted when the alias row trips the shared five-lens assertion).
#
# It executes the REAL assert_five_lens_rules defined by the target commit:
#   1. pass path: a real brief generated by bin/fm-brief.sh is accepted (exit 0).
#   2. failure path: the same brief with the alias row appended trips the
#      assertion; the emitted failure message is captured verbatim.
#   3. contrast: the assertion as landed by the parent work (64324e9, the PR #28
#      revision whose message the five-lens gate flagged) is run against the same
#      tampered brief to reproduce the reported "captain's alias" message.
set -u
ROOT=/home/martin_seibert/.no-mistakes/worktrees/e36b903ea8f4/01M2JG0RAND8WD3F86RSWW1YGN
cd "$ROOT" || exit 2

echo "repo: $ROOT"
echo "head: $(git rev-parse --short HEAD) $(git log -1 --format=%s)"
echo

echo "== 0. source the real test file (its full suite runs and must pass) =="
if . tests/fm-brief.test.sh >/dev/null 2>&1; then
  echo "ok - tests/fm-brief.test.sh sourced cleanly; its whole suite passed"
else
  echo "FAIL - tests/fm-brief.test.sh suite failed while sourcing"
  exit 2
fi

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/home/data"

for mode in direct-PR no-mistakes; do
  FM_HOME="$TMP/home" bin/fm-brief.sh "lens-$mode" some-proj --mode "$mode" >/dev/null || exit 2
done
brief_dpr="$TMP/home/data/lens-direct-PR/brief.md"
brief_nm="$TMP/home/data/lens-no-mistakes/brief.md"

echo
echo "== 1. pass path: real generated briefs satisfy the real assertion =="
for pair in "$brief_dpr|direct-PR" "$brief_nm|no-mistakes"; do
  b=${pair%%|*}
  label=${pair##*|}
  if (assert_five_lens_rules "$b" "$label") 2>/dev/null; then
    echo "ok - $label emitted DOD accepted by assert_five_lens_rules (exit 0, no message)"
  else
    echo "FAIL - $label emitted DOD rejected by assert_five_lens_rules"
    exit 2
  fi
done

echo
echo "== 2. failure path: alias row appended, message captured from the real assertion =="
tampered="$TMP/tampered-direct-PR.md"
cp "$brief_dpr" "$tampered"
printf '%s\n' '| architecture-system-design-reviewer | <yes or no> | <n> | <n> |' >> "$tampered"
message=$( (assert_five_lens_rules "$tampered" direct-PR) 2>&1 )
rc=$?
echo "exit code: $rc"
echo "emitted failure line: $message"
case "$message" in
  *"captain's alias"*)
    echo "FAIL - message still cites the captain's alias"
    exit 2 ;;
  *"must name the installed lens in the result table"*)
    echo "ok - message states what the result table must contain and cites no owner" ;;
  *)
    echo "FAIL - unexpected message"
    exit 2 ;;
esac

echo
echo "== 3. contrast: PR #28 revision (64324e9) reproduces the reported message =="
git show 64324e9:tests/fm-brief.test.sh \
  | sed -n '/^assert_five_lens_rules() {/,/^test_five_lens_gate_in_direct_pr_dod() {/p' \
  | sed '$d' > "$TMP/old-assert.sh"
# shellcheck disable=SC1090
. "$TMP/old-assert.sh"
old_message=$( (assert_five_lens_rules "$tampered" direct-PR) 2>&1 )
old_rc=$?
echo "exit code: $old_rc"
echo "emitted failure line: $old_message"
case "$old_message" in
  *"captain's alias"*)
    echo "ok - pre-change assertion reproduces the reported provenance citation" ;;
  *)
    echo "FAIL - could not reproduce the pre-change message"
    exit 2 ;;
esac

echo
echo "ALL CHECKS PASSED"
